"""thirds_revision

Revision ID: 0d46437bc552
Revises: cc552781a104
Create Date: 2023-04-19 16:51:30.191419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d46437bc552'
down_revision = 'cc552781a104'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_json',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relation_json_deleted'), 'relation_json', ['deleted'], unique=False)
    op.create_index(op.f('ix_relation_json_id'), 'relation_json', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relation_json_id'), table_name='relation_json')
    op.drop_index(op.f('ix_relation_json_deleted'), table_name='relation_json')
    op.drop_table('relation_json')
    # ### end Alembic commands ###
