"""second_revision

Revision ID: 422ee2939cfc
Revises: 43b681ec2eb5
Create Date: 2023-04-18 20:32:47.306706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422ee2939cfc'
down_revision = '43b681ec2eb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('union_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('open_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'open_id')
    op.drop_column('users', 'union_id')
    # ### end Alembic commands ###
