"""first_revision

Revision ID: 43b681ec2eb5
Revises: 
Create Date: 2023-04-18 20:12:40.346391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b681ec2eb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('another_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=20), nullable=True),
    sa.Column('describe', sa.String(length=200), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relation_deleted'), 'relation', ['deleted'], unique=False)
    op.create_index(op.f('ix_relation_id'), 'relation', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('regist_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('regist_ip', sa.String(), nullable=True),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_ip', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted'), 'users', ['deleted'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_deleted'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_relation_id'), table_name='relation')
    op.drop_index(op.f('ix_relation_deleted'), table_name='relation')
    op.drop_table('relation')
    # ### end Alembic commands ###
