"""third_revision

Revision ID: cc552781a104
Revises: cf91b537c91b
Create Date: 2023-04-19 13:50:18.518665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc552781a104'
down_revision = 'cf91b537c91b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_members_deleted'), 'group_members', ['deleted'], unique=False)
    op.create_index(op.f('ix_group_members_id'), 'group_members', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('note', sa.String(length=20), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_deleted'), 'groups', ['deleted'], unique=False)
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.add_column('relation', sa.Column('is_exposed', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('relation', sa.Column('is_view', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relation', 'is_view')
    op.drop_column('relation', 'is_exposed')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_deleted'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_group_members_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_deleted'), table_name='group_members')
    op.drop_table('group_members')
    # ### end Alembic commands ###
